apiVersion: apps/v1
kind: Deployment
metadata:
  name:  techtrends
  namespace: {{ .Values.namespace.name }}
  labels:
    app: techtrends
    tag: {{ .Values.image.tag }}
spec:
  selector:
    matchLabels:
      app: techtrends
      tag: {{ .Values.image.tag }}
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  techtrends
        tag: {{ .Values.image.tag }}
    spec:
      containers:
      - name:  techtrends
        image:  {{ .Values.image.repository }}
        resources:
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
        livenessProbe:
          httpGet:
            path: {{ .Values.livenessProbe.httpGet.path }}
            port: 3111
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: {{ .Values.readinessProbe.httpGet.path }}
            port: 3111
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        ports:
        - containerPort:  {{ .Values.containerPort }}
          name:  techtrends
      restartPolicy: Always