namespace:
  name: sandbox

service:
  port: 4111
  targetport: 3111
  protocol: TCP
  type: ClusterIP
image:
  repository: frkoichi/techtrends
  tag: latest
  pullPolicy: IfNotPresent
replicaCount: 1
resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi
containerPort:  3111
readinessProbe:
  httpGet:
    path: /healthz
livenessProbe:
  httpGet:
    path: /healthz
configmap:
  data: "version: latest"