apiVersion: v1
kind: Service
metadata:
  name: techtrends
  namespace: sandbox
spec:
  selector:
    app: techtrends
    tag: latest
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 300
  ports:
  - name: techtrends
    protocol: TCP
    port: 4111
    targetPort: 3111